# docker build . --file ./Dockerfile.2_delete_filelayer --tag my-2-delete-layer

FROM node:20-alpine
LABEL Name="Node.js Demo App" Version=4.9.9
ENV NODE_ENV=production
ENV MY_ENV_VARIABLE=abc123
WORKDIR /app

# For Docker layer caching do this BEFORE copying in rest of app
COPY src/package*.json ./
RUN npm install --production --silent

# NPM is done, now copy in the rest of the project to the workdir
COPY src/. .

RUN rm -r package*.json

# Port 3000 for our Express server 
EXPOSE 3000
ENTRYPOINT ["npm", "start"]
